on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 	185.151.30.203
        username: testerp@testerp.hhs-softwares-demo.top
        password: WiDi2a;xe]DX
